### ISSUE TITLE
Horses HP is broken.

### ISSUE THREAD

**Issue by K0-RR** [the-doo/x-hp#1]
Horses HP is dispayed as 50 or 53 but when hit it drops to 23 or something.

**Comment by the-doo** [comment]
> Horses HP is dispayed as 50 or 53 but when hit it drops to 23 or something.

thanks for you issues!

i check my code, and this wrong is minecraft

in 1.16.4 mc code, the horse have 53 HP in created, like this:

net.minecraft.entity.passive.HorseBaseEntity
 `   public static DefaultAttributeContainer.Builder createBaseHorseAttributes() {
      return MobEntity.createMobAttributes().add(EntityAttributes.HORSE_JUMP_STRENGTH).add(EntityAttributes.GENERIC_MAX_HEALTH, 53.0D).add(EntityAttributes.GENERIC_MOVEMENT_SPEED, 0.22499999403953552D);
   }`
EntityAttributes.GENERIC_MAX_HEALTH, 53.0D;
it mean, the created health num is 53.0D

and then, it will change when the horse health changed, like this:

net.minecraft.entity.LivingEntity
`   public void setHealth(float health) {
      this.dataTracker.set(HEALTH, MathHelper.clamp(health, 0.0F, this.getMaxHealth()));
   }`
MathHelper.clamp(health, 0.0F, this.getMaxHealth())
it mean, the new health num only between 0 ~ maxHealth(normal num)

for example:
horse created --> health 53, max health 23
you attack, damage 1
horse new health --> 53 - 1 = 52
52 > 23, horse new health --> 23

i hope i express clearly, thanks!!!
