### ISSUE TITLE
Issue with MobZ and MCDW

### ISSUE THREAD

**Issue by Karrtoffelbaer** [the-doo/x-hp#2]
With Enigma resonator 3 and over around 118 levels of xp on a sword with damage above 11 (vanilla limit on swords I think from testing), hitting a mob from the MobZ mod causes the game to crash.
I submitted the issue to the author of MCDW and he told me it had something to do with x hp.
[crash-2021-06-13_20.18.34-client.txt](https://github.com/15296500475/x-hp/files/6644750/crash-2021-06-13_20.18.34-client.txt)

**Comment by 15296500475** [comment]
> With Enigma resonator 3 and over around 118 levels of xp on a sword with damage above 11 (vanilla limit on swords I think from testing), hitting a mob from the MobZ mod causes the game to crash.
> I submitted the issue to the author of MCDW and he told me it had something to do with x hp.
> [crash-2021-06-13_20.18.34-client.txt](https://github.com/15296500475/x-hp/files/6644750/crash-2021-06-13_20.18.34-client.txt)

**Comment by the-doo** [comment]
I want to know your mod list to catch it, thanks!

I check the code and can't found cause by !!!

**Comment by githubbingitup** [comment]
I tested this problem myself using Enigma Resonator on various weapons with tons of EXP. I was hitting like 200+ damage a hit.
I spawned a bunch of mobs from Mobz to kill and no crashes ever occurred.

I don't think XHP is the cause. All seems to be working fine for me with the mod trio you mentioned.

Maybe submit this on the MobZ page.

**Comment by Karrtoffelbaer** [comment]
![image](https://user-images.githubusercontent.com/44552781/123520972-fb632180-d6b3-11eb-8eaa-8eadb946f936.png)
those are the mods im using

**Comment by githubbingitup** [comment]
Okay, then troubleshoot it.....
Remove all mods and add them back in one at a time until the problem happens again, loading up the game and testing it each time.

**Comment by Karrtoffelbaer** [comment]
after putting every mod back on and no crashes, it seems to be fixed ¯\_(ツ)_/¯

**Comment by the-doo** [comment]
Ok, may be this's a suprise on minecraft😀, have fun and thanks tell me!!!
