### ISSUE TITLE
Error Rendering Entity

### ISSUE THREAD

**Issue by githubbingitup** [the-doo/x-hp#3]
I got the exact same error as the user that posted this here. 
https://github.com/15296500475/x-hp/issues/2

I'm running a lot of mods, but it was a basic skeleton that made my game crash and I was doing nothing but idling.
I'm using Not Enough Crashes, as it tells the mods to blame. Here's the screen.
https://i.imgur.com/GTx3tG5.png

Here's the log.
[skele.txt](https://github.com/15296500475/x-hp/files/6721083/skele.txt)

**Comment by the-doo** [comment]
thanks, I catch it and fix on next version!!!
