### ISSUE TITLE
与Optifine，Optifabric一起运行时实体渲染出现bug

### ISSUE THREAD

**Issue by IceeAlin** [the-doo/x-hp#4]
宝 出bug了 xhp和optifine，optifabric放在一起的时候实体渲染出问题了qwq 当然也不排除是其他的mod导致的 我把mod列表贴出来吧
![image](https://user-images.githubusercontent.com/86223973/125173782-9cdd8d80-e1f3-11eb-93fa-c2743bbbc2f7.png)
接下来是bug效果
![java exe Screenshot 2021 07 11 - 02 53 18 37](https://user-images.githubusercontent.com/86223973/125173805-baaaf280-e1f3-11eb-8950-17c63e69d5bd.png)
![java exe Screenshot 2021 07 11 - 02 53 30 65](https://user-images.githubusercontent.com/86223973/125173808-bbdc1f80-e1f3-11eb-8d9a-98b810e99d85.png)
加油 争取把这bug修复了 冲冲冲

**Comment by the-doo** [comment]
不好意思，这段时间都没空看问题，我用 xhp和optifine，optifabric单独试了下 ,发现并没有问题，你看下是不是其他mod导致的或者是开了什么设置
