### ISSUE TITLE
Game crash - The secret of Shulkers

### ISSUE THREAD

**Issue by Kiryonn** [the-doo/x-hp#5]
Just trowing a harming potion to a Shulker makes the game crash and impossible to get back. When I reload the world the game crash so can't do anything :/
It does it when a shulker duplicate too. If you don't know what that is (but you probably do) it's when a shulker bullet hits a shulker (itself or not). When that happen the shulker have a chance to teleport leaving a new shulker behind.

I used haming II (didn't tested with harming 1) and it was in creative (didn't tested in survival).

**Comment by the-doo** [comment]
can you paste the error info?

thanks!!!

**Comment by the-doo** [comment]
i check it, and fix it on new one
