### ISSUE TITLE
Disabling tips, disables everything.

### ISSUE THREAD

**Issue by egeesin** [the-doo/x-hp#8]
### Intention:
Hiding only tip text at top-left corner.

### How to reproduce:
- *Mod is already in enabled state.* Clicking on "Enabled Tips: ON" to turn off.

**Comment by the-doo** [comment]
Mod and tips enabled, but tips not show on top-left?

Can you try to set Trigger Option: In Around?

**Comment by egeesin** [comment]
I don't know if setting Trigger Option is directly related but I think I found out why the issue happens. The core of the problem is the communication between config GUI and ``doo.json`` itself. If I click on "Enable Tips", it changes the ``"enabled": ...,`` line instead of `` "tips": ...,`` line. I manually edited the json config file like below:
```json
    "enabled": true,
    "trigger": "FOCUS",
    "tips": false,
```
After restarting the game without doing nothing in the config GUI, it adjusted how I wanted.

Edit: Forgot to mention your first question, I want to enable the mod and disable the tips.

**Comment by the-doo** [comment]
Thanks, I got it!

Error code is com.doo.xhp.menu.screen.ModMenuScreen#TIPS

`    private static final Option TIPS = CyclingOption.create(
            "xhp.menu.option.tips",
            o -> XHP.XOption.enabled,
            (g, o, v) -> XHP.XOption.enabled= v);
`

So, Tips option button will change Enabled Option value😂

I will fix later, thanks  again~~~
