### ISSUE TITLE
[Feature] Option to hide overlay when HUD is hidden

### ISSUE THREAD

**Issue by egeesin** [the-doo/x-hp#9]
As the title says, there should be an option to hide overlay whenever HUD is hidden. (enabled by the default since this is makes more sense as more expected behaviour)

**Comment by the-doo** [comment]
Sorry brother, my english is so pool, maybe you mean that click F5 button will effect on entity HP or Tips?

Like this: 
Hotbar hidden, HP and Icon will hidden too

If I guess right your issue, I will add the option in next version

Or you can try to clear again😀

**Comment by egeesin** [comment]
No worries! Yes, this is exactly what I told.

Edit: Also it's F1 instead of F5.

**Comment by the-doo** [comment]
I'm done and will publish to curseforge in some hours later

or you can download in github, if you want...

Thanks your nice issue
